// :::::::::::::::::::::::: LICENSE AND COPYRIGHT NOTICE :::::::::::::::::::::::
// Copyright (c) 2014 Nick Foster <bistromath@gmail.com>.  All rights reserved.
// 
// This file is part of Chroma.  Chroma is distributed under the GNU General
// Public License, Version 3.0.  You can read the full terms of use in the
// COPYING file, or online at http://www.gnu.org/licenses/gpl.html.
// :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

/* This file is automatically generated. Do not edit. */

#include <Chroma/Types/spd.hpp>
namespace Chroma {

/* CIE1931 photopic efficiency curve */
const Chroma::spd CIE1931_photopic_eff({380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770, },{3.9000000e-05, 1.2000000e-04, 3.9600000e-04, 1.2100000e-03, 4.0000000e-03, 1.1600000e-02, 2.3000000e-02, 3.8000000e-02, 6.0000000e-02, 9.0980000e-02, 1.3902000e-01, 2.0802000e-01, 3.2300000e-01, 5.0300000e-01, 7.1000000e-01, 8.6200000e-01, 9.5400000e-01, 9.9495000e-01, 9.9500000e-01, 9.5200000e-01, 8.7000000e-01, 7.5700000e-01, 6.3100000e-01, 5.0300000e-01, 3.8100000e-01, 2.6500000e-01, 1.7500000e-01, 1.0700000e-01, 6.1000000e-02, 3.2000000e-02, 1.7000000e-02, 8.2100000e-03, 4.1020000e-03, 2.0910000e-03, 1.0470000e-03, 5.2000000e-04, 2.4900000e-04, 1.2000000e-04, 6.0000000e-05, 3.0000000e-05, });

} /* namespace Chroma */
